import html
from django.shortcuts import render
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from datetime import datetime, timezone
import urllib.parse
from postgres_connection import create_connection

#QUERY VIOLATIONS with SCOFFLAW
# aggregate scofflaws - count number of scofflaws
QUERY_VIOLATIONS_BYADDRESS = """
SELECT
v.*,
COALESCE(s.scofflaw_count, 0) AS scofflaw_count
FROM violations v
LEFT JOIN (
    SELECT
        address,
        COUNT(*) AS scofflaw_count
    FROM scofflaw
    GROUP BY address
    ) s
    ON v.address = s.address
WHERE v.address = %s
"""

#JOIN TABLES BY VIOLATIONS QUERY
QUERY_SCOFFLAWS_BYDATE = """
SELECT
s.*,
v.violation_date,
v.violation_description
FROM scofflaw s
LEFT JOIN violations v
    ON s.address = v.address
"""

#INSERT COMMENT - author, address, comment
QUERY_INSERT_COMMENT = """
INSERT INTO comments (author, datetime, address, comment)
VALUES (%s, NOW(), %s, %s)
RETURNING address, comment;
"""


def query_data_singlevalue(query, value):
    try:
        conn = create_connection()
        cursor = conn.cursor()
        if(value):
            cursor.execute(query, [value])
        else:
            cursor.execute(query)
        columns = [col[0] for col in cursor.description]
        results = [dict(zip(columns, row)) for row in cursor.fetchall()]
        return results
    except Exception as e:
        print(e)
        return -1


#GET REQUEST get violations by address
@api_view(['GET'])
def get_data(request, address):
    decoded_address = urllib.parse.unquote(address).strip().upper()
    results = query_data_singlevalue(QUERY_VIOLATIONS_BYADDRESS, decoded_address)
    if not results:
        return Response({"error": "No records found"}, status=status.HTTP_404_NOT_FOUND)
    if results == -1:
        return Response({"error": "Database error"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
    
    #parse results for property violations and scofflaw
    response_content = {
        'last_violation_date': max(list(map(lambda item: (item['violation_date']), results))),
        'total_violations': len(results),
        'scofflaw': True if max(list(map(lambda item: (item['scofflaw_count']), results)))>0 else False,
        'violations': results
        }
    return Response(response_content, status=status.HTTP_200_OK)


#GET scofflaw violations
@api_view(['GET'])
def get_scofflaw_violations(request):
    since = request.query_params.get('since', '').strip()
    print(since)
    if(since):
        try:
            query = QUERY_SCOFFLAWS_BYDATE
            query += "WHERE v.violation_date >= %s"
            since_date = datetime.strptime(since, "%Y-%m-%d").date()
            results = query_data_singlevalue(query, since_date)
        except ValueError:
            return Response({"Error": "Invalid date format. Use YYYY-MM-DD."}, status=status.HTTP_400_BAD_REQUEST)
    else:
        #get all scofflaws?
        results = query_data_singlevalue(QUERY_SCOFFLAWS_BYDATE, "")

    if not results:
        return Response({"error": "No records found"}, status=status.HTTP_404_NOT_FOUND)
    if results == -1:
        return Response({"error": "Database error"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
    #parse results
    #get list of addresses
    response_content = list(set(map(lambda item: (item['address']), results)))
    return Response(response_content, status=status.HTTP_200_OK)


# POST comment for address url http://127.0.0.1:8000/property/<str:address>/comments/
# post data only needs author and comment.
# address is from url
# timestamp will be generated by table
@api_view(['POST'])
def add_comment(request, address):
    print(f"property address {address}")
    try:
         # Extract data from request
        author = request.data.get('author')
        comment = request.data.get('comment')
        address = address.strip().upper()

        if not author or not comment:
            return Response({"error": "author and comment are required"}, status=status.HTTP_400_BAD_REQUEST)
        
        #sanitize data - strip, html escape, remove all non alphanumeric and apostrophes
        author = html.escape(author.strip().replace(r"[^a-zA-Z0-9']", ''))
        comment = html.escape(comment.strip().replace(r"[^a-zA-Z0-9']", ''))

        #insert data
        try:
            conn = create_connection()
            cursor = conn.cursor()
            cursor.execute(QUERY_INSERT_COMMENT, (author, address, comment))
            comment_id = cursor.fetchone()
            conn.commit()
            cursor.close()
            conn.close()
            return Response({
                "status": "success",
                "message": "Comment added successfully.",
                'comment_added': comment_id}, status=status.HTTP_201_CREATED)
        except Exception as e:
            return Response({"error": "Database error"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        
    except Exception as e:
        return Response({"error": "Database error"},status=status.HTTP_500_INTERNAL_SERVER_ERROR)